name: ngx-file-upload/core

on: [push]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - name: install dependencies
        run: |
          cd src
          npm i

      - name: add @angular/cli global
        run: |
          npm i -g @angular/cli
          ng --version

      - name: lint
        run: |
          cd src
          npm run lint -- core

      - name: build packages
        run: |
          cd src
          npm run build -- core

      - name: unit tests
        run: |
          cd src
          npm run github-actions:unit-tests-core

      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./src/coverage/core/report-lcov/lcov.info
          flags: core
