name: ngx-file-upload/ui

on: [push]

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          cd src
          npm i
          npm i puppeteer@chrome-78
          npm run webdriver:update

      - name: add @angular/cli global
        run: |
          npm i -g @angular/cli@17.3.4
          ng version

      - name: lint
        run: |
          cd src
          npm run lint -- ui

      - name: build packages
        run: |
          cd src
          npm run build -- core
          npm run build -- ui
